# Generated by Django 2.0.3 on 2018-03-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_tweet_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='coordinates',
            field=models.TextField(null=True),
        ),
    ]
